### ISSUE TITLE
Exits with 0-code when exercise test fails

### ISSUE THREAD

**Issue by denysdovhan** [workshopper/workshopper-adventure-test#31]
Here's a log: https://travis-ci.org/workshopper/how-to-markdown/jobs/206894189#L250-L323

**Comment by denysdovhan** [comment]
**UPD:** The same situation with other test, process exits with zero-code even when test fails.

**Comment by martinheidegger** [comment]
The [update of mocha](https://github.com/workshopper/workshopper-adventure-test/commit/de1f37b25a5338651bd46221d5357fc3c36c30b5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R39) seems to have caused this problematic.  _(Will fix this in a minute)_

**Comment by martinheidegger** [comment]
Published as [1.1.1](https://github.com/workshopper/workshopper-adventure-test/releases/tag/v1.1.1)
